# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/quantitydb
spring.datasource.username=root
spring.datasource.password=Aryan@123

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret (use a 256-bit base64 string in production)
jwt.secret=MySuperSecretKeyForJWTQuantityApp12345678
jwt.expiration=86400000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=my client id
spring.security.oauth2.client.registration.google.client-secret=my secret key
#spring.security.oauth2.client.registration.google.scope=email,profile